### PR TITLE
feat: use entry hooks for injection in Webpack 5

### LINKED ISSUE #293: Does not rerender with webpack 5 + babel 7 (test repo included)
Hi. I can't get to work the live refresh. My setup is:
```
  "dependencies": {
    "react": "^17.0.1",
    "react-dom": "^17.0.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.10",
    "@babel/preset-react": "^7.12.10",
    "@pmmmwh/react-refresh-webpack-plugin": "^0.4.3",
    "babel-loader": "^8.2.2",
    "react-refresh": "^0.9.0",
    "webpack": "^5.13.0",
    "webpack-cli": "^4.3.1",
    "webpack-dev-server": "^3.11.2"
  }

```

I get the following text on the console on firefox:
```
[WDS] App updated. Recompiling...
[WDS] App hot update...
[HMR] Checking for updates on the server...
[HMR] Updated modules:
[HMR]  - ./src/test-component.js
[HMR] App is up to date.
```

But the content does not update.

You can see my webpack config and a test repo i did in: https://github.com/franz-ka/react-refresh-test

I also tested with `webpack-dev-server@4.0.0-beta.0` without luck.

Thx, hope i can use this plugin because i wish to migrate from hot-reloader!

### LINKED ISSUE #303: Hot reloading tested in different ways and is not working properly
- **Operating System:** _macOS Big Sur 11.2_
- **Node Version:** _v14.15.4_
- **NPM Version:** _6.14.10_
- **webpack Version:** _^5.19.0_
- **webpack-dev-server Version:** _^4.0.0-beta.0_
- **Browser:** _Google Chrome Version 88_

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

Repository link: https://github.com/Ridermansb/webpack5Hot

 - [`master`](https://github.com/Ridermansb/webpack5Hot) branch it's using only basic webpack-dev-server configuration without any plugins
 - [`react-hot-loader`](https://github.com/Ridermansb/webpack5Hot/tree/react-hot-loader) branch it's using [react-hot-loader](https://github.com/gaearon/react-hot-loader) plugin. **[Pull Request #1](https://github.com/Ridermansb/webpack5Hot/pull/1)**
 - [`react-refresh-webpack-plugin`](https://github.com/Ridermansb/webpack5Hot/tree/react-refresh-webpack-plugin) branch it's using [pmmmwh/react-refresh-webpack-plugin](https://github.com/pmmmwh/react-refresh-webpack-plugin) webpack plugin. **[Pull Request #2](https://github.com/Ridermansb/webpack5Hot/pull/2)**

### Expected Behavior

In all case... should not reload the page and only reload the portion that's changed

### Actual Behavior

It's Always reloading the entire page.

### For Bugs; How can we reproduce the behavior?

Just clone the repository [ridermansb/webpack5Hot](https://github.com/Ridermansb/webpack5Hot) 

 - `npm install`
 - `npm start`

And try update `Header` component

### LINKED ISSUE #346: Webpack 5: plugin don't work if no entry specified in webpack config
Reproduce demo for this and #347 
https://github.com/farwayer/rrwp-issues

### LINKED ISSUE #398: __REACT_DEVTOOLS_GLOBAL_HOOK__ doesn't installed when there is no entry in the config
By default, webpack will have a default entry `main: ./src/index`. If I use that default entry, `__REACT_DEVTOOLS_GLOBAL_HOOK__ ` will not be installed thus I cannot use react-refresh

### PR DESCRIPTION
**Pull request by pmmmwh**
Fixes #293 
Fixes #303 
Fixes #346 
Fixes #398

### CODE REVIEW

**Comment by amerllica** [comment]
@pmmmwh , Thanks mike, please bring for us Webpack 5 support, really world of ReactJS developers need this.

**Comment by pmmmwh** [comment]
@amerllica 
Webpack 5 support is already there. This is just a quality of life improvement and try to stick to newer Webpack conventions. FYI I'm not prioritizing on this PR because it does not block usage.

**Comment by chang-ke** [comment]
Hi Michael~ I want to know when to release this PR？ I really need it.

**Comment by pmmmwh** [comment]
@chang-ke why do you need it? Webpack 5 is already officially supported even without this PR. I'm not planning to finish this PR any time soon.

**Comment by chang-ke** [comment]
> @chang-ke why do you need it? Webpack 5 is already officially supported even without this PR. I'm not planning to finish this PR any time soon.

Now i'm use dynamic entry, so without this pr, injectEntry doest not work

**Comment by pmmmwh** [comment]
Can you explain your use case further with the help of some examples?

**Comment by amerllica** [comment]
@pmmmwh , What do you mean:
>Webpack 5 support is already there.

>Webpack 5 is already officially supported

Webpack is a tool for bundling, ReactJS is a library, The Webpack developers haven't made it for specific library. why you said those?

**Comment by pmmmwh** [comment]
TODO:

- Cleanup imports
- Cleanup socket entry check
- Document heuristic change

**Comment by pmmmwh** [comment]
> Webpack is a tool for bundling, ReactJS is a library, The Webpack developers haven't made it for specific library. why you said those?

@amerllica 

React Refresh is built on top of bundlers' native HMR capabilities. To support a specific bundler (version), we need to have the proper code to hook React Refresh into the HMR lifecycle.

Webpack 5 is supported means this plugin will allow you to have React Refresh capabilities if you use Webpack 5 as your bundler. However without this PR there is a small caveat that you cannot rely on Webpack 5's default entry point (`./src`) and have to manually specify your entry, because we rely on that to inject stuff for you.

@chang-ke 

This should make it into the next beta, which will probably be the last one before `0.5.0` lands.

**Pull request merged**
