### PR TITLE
chore(deps-peer): relax peer dependency on type-fest

### LINKED ISSUE #244: type-fest peer dependency warning
NPM warns that v0.4.3 requires a peer of type-fest@^0.13.1 when type-fest@^0.17.0 is installed.
Would it be possible to use **_"type-fest": ">=0.13.1"_** instead of **_"type-fest": "^0.13.1"_**?

### PR DESCRIPTION
**Pull request by pmmmwh**
This fixes #244

### CODE REVIEW

**Comment by paulrosania** [comment]
Hi! Any chance of a release including this change? npm 7 went GA today, and the new `peerDependencies` resolution makes this PR extra helpful! 🤞🏼

**Comment by pmmmwh** [comment]
Hi, this is already in the latest beta. Unfortunately I have been really busy lately, hopefully the next release can come out in a week or two.

**Comment by dflynn15** [comment]
Thanks for doing this in beta! Could there also be a patch version for `0.4.3` -> `0.4.4` that also relaxes the peer dependency?

**Comment by pmmmwh** [comment]
Hi - I'm not planning to back port this since the stable release for `0.5.x` will be here soon (only outstanding task is ESM-related stuff which I'm actively working on). There are no breaking changes in the API so upgrading should be easy.

**Comment by kenziebottoms** [comment]
Any updates on either a patch version or 0.5.x?

**Comment by pmmmwh** [comment]
> Any updates on either a patch version or 0.5.x?

The RC (`0.5.0-rc.0`) is already here, which is stable.

**Comment by pmmmwh** [comment]
> When will `0.5.x` be officially released? I am still getting the error from `react-scripts` from issue #244 because react-scripts still uses 0.4.x

CRA v5 will be using `0.5.x`. For now, I do not have a concrete release date when `0.5.x` will be stable - I'm working on patching all the known bugs and release it, but all the remaining ones are quite tricky, but I still hope to release this soon.

**Pull request merged**
