### PR TITLE
feat: support webpack-plugin-serve

### PR DESCRIPTION
**Pull request by pmmmwh**
This have previously been requested in #10 and #51, so I've decided to make this built in for better support down the road.

CC @shellscape @PlayMa256 @sibelius - Would love to have your input on whether the implementation looks fine, because I really don't have much knowledge on `webpack-plugin-serve`.

One thing that is missing is the syntax highlighting for the Webpack errors, which is achieved in `webpack-dev-server` and `webpack-hot-middleware` by parsing ANSI information from the socket message. WPS on the other hand, strips away all the info before sending out the message, so there's no way we will be able to reconstruct that behaviour here.

### CODE REVIEW

**Comment by shellscape** [comment]
Thanks for pinging me here!

> WPS on the other hand, strips away all the info before sending out the message

Can you detail what information you'd need to keep things working on your end? I'd be happy to enable a more verbose info transfer.

**Comment by pmmmwh** [comment]
> Can you detail what information you'd need to keep things working on your end? I'd be happy to enable a more verbose info transfer.

Its basically [this line](https://github.com/shellscape/webpack-plugin-serve/blob/aeb49f14e900802c98df4a4607a76bc67b1cffdf/lib/routes.js#L61) (and the line for warnings) that needs some change. WDS/WHM's overlay works,by sending the non-stripped ANSI-encoded stats message via sockets and then highlight them with `ansi-html`.

To be fair, I'm not sure if this is a good way - but the way that the overlay in this plugin is [implemented](https://github.com/pmmmwh/react-refresh-webpack-plugin/blob/e728c1a0a0b64508a9b435373a5c2c0ba3a0a9a7/src/overlay/components/CompileErrorTrace.js#L32), I'm pretty sure if you can send out the highlighted HTML and I can make them display correctly.

**WDS**

Screenshot 2020-04-18 at 4 58 38 PM

**WPS**

Screenshot 2020-04-18 at 5 03 19 PM

**Comment by shellscape** [comment]
@sibelius / @PlayMa256 can either of you check this out?

**Comment by PlayMa256** [comment]
> @sibelius / @PlayMa256 can either of you check this out?

i'll be picking this up this evening!

**Comment by PlayMa256** [comment]
hi @pmmmwh https://github.com/shellscape/webpack-plugin-serve/tree/fix/ansi can you try this branch please?

Let us know if it works! We can merge and release one from this!

**Comment by pmmmwh** [comment]
> Let us know if it works! We can merge and release one from this!

I'll test it tonight 👍

**Comment by pmmmwh** [comment]
> Let us know if it works! We can merge and release one from this!

Hi @PlayMa256 - Your branch fixes the issue for this plugin, but it breaks the native overlay in `webpack-plugin-serve`.

Screenshot 2020-05-06 at 7 03 29 PM

I suppose you will have to strip ANSI within the overlay (to keep the previous behaviour) or add something like `ansi-html` in it to parse the ANSI syntax and add syntax highlighting to the overlay.

Either way - the integration is working here, so I'll merge this branch first. Please notify me when you merge the PR so that I can update the depended version of WPS 👍

**Comment by pmmmwh** [comment]
Landed in `0.3.0-beta.6` :tada:

**Comment by TrySound** [comment]
By the way, there is v1 of this plugin. Now I get peer dependency warning.
https://github.com/shellscape/webpack-plugin-serve/releases/tag/v1.0.0

**Comment by pmmmwh** [comment]
> By the way, there is v1 of this plugin.

I'll bump the peer dependency.

**Comment by TrySound** [comment]
I don't think so.

**Comment by pmmmwh** [comment]
> I don't think so.

Requirement relaxed in `v0.3.1`.

**Pull request merged**
