### PR TITLE
feat: automatic DOM URL ponyfilling

### PR DESCRIPTION
**Pull request by pmmmwh**
This PR adds out of the box pony-filling capabilities for the DOM URL API.

### CODE REVIEW

**Comment by DinerIsmail** [comment]
Any chance you could release a new version that includes this fix please?

**Comment by pmmmwh** [comment]
> Any chance you could release a new version that includes this fix please?

It is in 0.5.0 beta. If you need a stable version then you'll have to wait a bit since there are other stuff yet to be fixed.

**Comment by dineshpannu** [comment]
I'm trying this on IE 11 and can't get it to work. 

The error is: 
> stack	"TypeError: Unable to get property 'toLowerCase' of undefined or null reference\n   at initWDSSocket (eval code:26:5)\n   at setupOverlay (eval code:86:7)\n   at runWithPatchedUrl (eval code:36:3)\n   at eval code (eval code:82:4)\n   at ../../node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ErrorOverlayEntry.js?sockPort=8080&sockProtocol=http (http://192.168.0.120:8080/Content/JS/client.app.js:248:1)\n   at options.factory (http://192.168.0.120:8080/Content/JS/client.app.js:6925:28)\n   at __webpack_require__ (http://192.168.0.120:8080/Content/JS/client.app.js:6410:48)\n   at Anonymous function (http://192.168.0.120:8080/Content/JS/client.app.js:7490:26)\n   at Anonymous function (http://192.168.0.120:8080/Content/JS/client.app.js:19:1)\n   at webpackUniversalModuleDefinition (http://192.168.0.120:8080/Content/JS/client.app.js:17:3)"

Packages used:
- react-refresh@0.10.0
- @pmmmwh/react-refresh-webpack-plugin@0.5.0-beta.8
- webpack@5.31.2
- webpack-dev-server@3.11.2 

Webpack config looks like:
```
    plugins: [
        new ReactRefreshWebpackPlugin({
            overlay: {
                useURLPolyfill: true // this is for IE 11
            }
        }),
    ],
```

**Comment by pmmmwh** [comment]
I didn't realise that IE does not support `toLowerCase` 😬 Will fix.

**Pull request merged**
