### PR TITLE
fix: allow proper CRA usage

### LINKED ISSUE #8: Server startup hangs forever (or a really long time?) if disableRefreshCheck=false
I have to set `disableRefreshCheck: true` in order to successfully start up the webpack-dev-server, otherwise the startup seems to hang (I waited minutes, but not hours).

This is observable both on an ejected CRA app patched using instructions from the README as well as an existing CRA app that uses react-app-rewired/customize-cra.

### LINKED ISSUE #14: Fails to work when integrated into create-react-app
The error I am seeing is. Please let me know if there's anything else you need.

```
createSocket.js:30 Uncaught TypeError: connection.onClose is not a function
    at createSocket (createSocket.js:30)
    at Object../node_modules/react-refresh-webpack-plugin/src/runtime/ErrorOverlayEntry.js (ErrorOverlayEntry.js:85)
    at __webpack_require__ (bootstrap:785)
    at fn (bootstrap:150)
    at Object.0 (theme.ts:23)
    at __webpack_require__ (bootstrap:785)
    at checkDeferredModules (bootstrap:45)
    at Array.webpackJsonpCallback [as push] (bootstrap:32)
    at main.chunk.js:1
```

```
❯ npm ls react-refresh react-refresh-webpack-plugin webpack-dev-server webpack
frontend@1.1.13 /Users/xxx/frontend
├── react-refresh@0.7.0
├── react-refresh-webpack-plugin@0.1.0
└─┬ react-scripts@3.2.0
  ├── webpack@4.41.0
  └── webpack-dev-server@3.2.1
```

Taken from https://github.com/facebook/react/issues/16604#issuecomment-561967793
```js
const { addBabelPlugin, addWebpackPlugin, override } = require('customize-cra');
const ReactRefreshPlugin = require('react-refresh-webpack-plugin');

/**
 * @param {ReactRefreshPluginOptions} [options] Options for react-refresh-plugin.
 */
const addReactRefresh = options =>
  override(
    process.env.NODE_ENV === 'development'
      ? addBabelPlugin('react-refresh/babel')
      : undefined,
    process.env.NODE_ENV === 'development'
      ? addWebpackPlugin(new ReactRefreshPlugin(options))
      : undefined
  );

/* config-overrides.js */
module.exports = override(addReactRefresh({ disableRefreshCheck: true }));
```

### PR DESCRIPTION
**Pull request by pmmmwh**
This fixes the issues surrounding the Babel transform detection when `node_modules` JS files are either externalized (processed with another Babel config) or completely non-processed (e.g. TS project) and also issues related to the fallback `SockJS` integration.

The plugin will now split out a proper warning instead of error out and thus halts compilation. I have yet to think of a proper way to detect Babel transforms without using multiple conditional `RegExp`/AST matches, but to unblock people from using the plugin I think we should get this shipped for now.

Fixes #8
Fixes #14 
Partially addresses #11 and #15 but would love to do better - discussion started in #15.

### CODE REVIEW

**Comment by allocenx** [comment]
Nice. And when do we get a new release? I really need this plugin asap. Thank you for the amazing work.

**Comment by pmmmwh** [comment]
> Nice. And when do we get a new release? I really need this plugin asap. Thank you for the amazing work.

Most likely tomorrow if I don't get occupied by other stuff.

**Comment by allocenx** [comment]
> > Nice. And when do we get a new release? I really need this plugin asap. Thank you for the amazing work.
> 
> Most likely tomorrow if I don't get occupied by other stuff.

Thank you. Will wait.

**Comment by gaearon** [comment]
Don't forget that if it gets too complicated, we can just punt on detection altogether. It doesn't have to be a huge unbounded pile of hacks.

**Comment by pmmmwh** [comment]
> Don't forget that if it gets too complicated, we can just punt on detection altogether. It doesn't have to be a huge unbounded pile of hacks.

Yea definitely, but I think there are still stuff that I haven't tried if it will work, and I am feeling adventurous :rofl:

**Comment by pmmmwh** [comment]
> > > Nice. And when do we get a new release? I really need this plugin asap. Thank you for the amazing work.
> > 
> > 
> > Most likely tomorrow if I don't get occupied by other stuff.
> 
> Thank you. Will wait.

Released. :tada:

**Comment by allocenx** [comment]
> > > > Nice. And when do we get a new release? I really need this plugin asap. Thank you for the amazing work.
> > > 
> > > 
> > > Most likely tomorrow if I don't get occupied by other stuff.
> > 
> > 
> > Thank you. Will wait.
> 
> Released. 🎉

Uhm un release page i still see only the v0.1.0 version...

**Comment by allocenx** [comment]
Still not working, now receiving just: 

> WARNING in React Refresh Plugin: The plugin is unable to detect transformed code from react-refresh. Did you forget to include "react-refresh/babel" in your list of Babel plugins? Note: you can disable this check by setting "disableRefreshCheck: true".


I 100% followed the exact guide and i still got that.

Rule for JS:

`exclude: /node_modules/,
  test: /\.js?$/,
  use: {
    loader: 'babel-loader',
    options: {
      presets: ["@babel/preset-env", "@babel/preset-react"],
      plugins: ["react-refresh/babel"]
    }
  }`

Added into plugins too:

`plugins.push(
          new ReactRefreshWebpackPlugin()
        )
`

Why is this still not working?

**Comment by pmmmwh** [comment]
> Why is this still not working?

It is because the detection still don't work properly. Everything fixed was about CRA/Webpack crashing silently, but not related to the detection. I am actively trying out other solutions to reduce false negatives, but that requires a lot of trial and error. I know it is noisy, I will add a note in the README to indicate that it is broken.

**Pull request merged**
