### PR TITLE
feat: set react-refresh globals on Webpack require instead of global scope

### LINKED ISSUE #88: Multiple entry points not working correctly
Our team has a config with the form:

```
{
  ...
  entry: {
    entry1: ['file1', 'file2'],
    entry2: ['file3', 'file4'],
  }
}
```

We were very excited to try out `react-refresh-webpack-plugin`, but unfortunately, could not get it working!

Through a process of trial and error, I removed `entry2`, and it started working. I think this is due to the logic in `injectRefreshEntry`, which would double-append react refresh into both entries. Is this intentional behavior?

Thanks!
Mike

### PR DESCRIPTION
**Pull request by pmmmwh**
This PR moves all react-refresh related globals to Webpack's require function instead of renderers' global scope.

This eliminates issues related to:
- Renderers that do not have `window` defined
- Electron/WebWorker/Native-related usage
- Multiple bundles included for the same page

Fixes #88.
Related to #36 and #79.

CC @sokra - if possible please take a look at this (possible issues/optimizations?)

### CODE REVIEW

**Comment by michaelgmiller1** [comment]
Very excited for this!! If you need any help testing, happy to lend a hand!

**Comment by manelio** [comment]
About the point

> Multiple bundles included for the same page

That fixes #88:

I modified the webpack-dev-server example this way:

webpack.config.js:
```
...
  entry: {
    main1: './src/index1.js',
    main2: './src/index2.js',
  },
...
```

public/index.html:
```
...
  <body>
    <div id="app1"></div>
    <div id="app2"></div>
  </body>
...

```

src/index1.js:
```
import * as React from 'react';
import { render } from 'react-dom';
import App1 from './App1';
render(<App1 />, document.getElementById('app1'));
```

src/App1.jsx:
```
import * as React from 'react';

function App1() {
  return <h1>Test1</h1>;
}

export default App1;

```

And similarly for index2.js and App2.jsx.

But the behavior is, if I made a change in App1.jsx, the DOM is updated, but nothing happens if I modify App2.jsx.

What does it mean "Multiple bundles included for the same page"? Is not this case?

**Comment by pmmmwh** [comment]
> What does it mean "Multiple bundles included for the same page"? Is not this case?

Sorry I cannot dig into this right now, this might be a regression somewhere.

Can you try make both bundles share the same instance of React and React DOM and see if it works?

**Comment by pmmmwh** [comment]
@manelio

Just add this to your Webpack config, it should work:

```js
module.exports = {
  // ... Other stuff
  optimization: {
    runtimeChunk: 'single',
  },
};
```

**Comment by vaishnavi1029** [comment]
TypeError: $RefreshSig$ is not a function
I am writing tests and getting these error this when I am trying to check before and after context values change.
can you let me know why is this happening and how should I potentially eliminate it

**Comment by pmmmwh** [comment]
You probably shouldn't apply `react-refresh/babel` when running tests.

**Pull request merged**
